
spring:
  datasource:
    username: root
    password: lz_123@456.com
    url: jdbc:mysql://localhost:3306/world
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

# 持久化日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl